// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
   CodegenLoader();

  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static  Map<String,dynamic> ar = {
  "test": "تجربه",
  "choose_your_elevator": "اختر مصعدك",
  "elevator_company_intro": "تقدم شركة أكنان للمصاعد أنواعًا مختلفة من المصاعد المناسبة للأفراد والشركات والمراكز التجارية.",
  "maintenance_service": "خدمة الصيانة",
  "elevator_company_intro_2": "تقدم لك أكنان فريقًا متكاملًا من الفنيين لإصلاح الأعطال وإجراء صيانة دائمة",
  "spare_parts": "قطع الغيار",
  "elevator_company_intro_3": "تقدم شركة أكنان للمصاعد لك جميع قطع الغيار اللازمة لصيانة شاملة لجميع أنواع المصاعد.",
  "Phone_number": "رقم الهاتف",
  "get_started": "قم بالبدء",
  "Password": "كلمة السر ",
  "forgot_password ": "هل نسيت كلمة السر ؟",
  "Verify": "تاكيد",
  "your_phone": "ادخل رقم هاتفك",
  "home": "الرئيسية",
  "chat": "الدردشة",
  "profile": "الملف الشخصي",
  "settings": "الإعدادات",
  "policies_privacy": "السياسات والخصوصية",
  "contact_us": "اتصل بنا",
  "change_password": "تغيير كلمة المرور",
  "complete_data": "إكمال البيانات",
  "login": "تسجيل الدخول",
  "otp_login": "تسجيل الدخول برمز التحقق",
  "or": "او",
  "do_not_have_an_account": "ليس لديك حساب؟",
  "sign_up": "اشتراك",
  "enter_verification_code": "أدخل رمز التحقق",
  "did_not_receive_the_code": "لم يتلق OTP",
  "resend_it": "إعادة إرسال",
  "reset_password": "إعادة تعيين كلمة المرور",
  "save": "حفظ",
  "skip": "يتخطى",
  "enter_your_verified_phone_number": "أدخل رقم هاتفك الذي تم التحقق منه",
  "send": "إرسال",
  "name": "الاسم",
  "email": "البريد الإلكتروني",
  "government": "الحكومة",
  "city": "المدينة",
  "district": "الحي",
  "confirm_password": "تأكيد كلمة المرور",
  "old_password": "كلمة المرور القديمة",
  "new_password": "كلمة المرور الجديدة",
  "confirm_new_password": "تأكيد كلمة المرور الجديدة",
  "update": "تحديث",
  "types_of_elevators": "أنواع المصاعد",
  "maintenance_requests": "طلبات الصيانة",
  "periodic": "دورية",
  "emergency": "طارئة",
  "complaint": "شكاوي",
  "Periodic": "دورية",
  "Emergency": "طارئة",
  "Complaint": "شكاوي",
  "notification": "إشعارات",
  "change_language": "تغيير اللغة",
  "theme": "السمة",
  "about_us": "معلومات عنا",
  "policies_and_privacy": "السياسات والخصوصية",
  "log_out": "تسجيل الخروج",
  "contract_type": "نوع العقد",
  "start_date": "تاريخ البداية",
  "end_date": "تاريخ الانتهاء",
  "periodic_maintenance": "الصيانة الدورية",
  "emergency_maintenance": "الصيانة الطارئة",
  "complaint_maintenance": "صيانة الشكاوى",
  "time_and_date": "الوقت والتاريخ",
  "employee": "الموظف",
  "cost": "التكلفة",
  "damage": "الضرر",
  "maintenance_work": "أعمال الصيانة",
  "yes": "نعم",
  "no": "لا",
  "change_password_confirmation": "هل أنت جاد بشأن تغيير كلمة المرور؟",
  "change_language_confirmation": "هل أنت جاد بشأن تغيير اللغة؟",
  "ar": "العربية",
  "en": "الإنجليزية",
  "request_maintenance": "طلب صيانة",
  "malfunctions": "أعطال",
  "submit": "إرسال",
  "next": "التالي",
  "send_otp": "إرسل رمز",
  "elevator_code": "كود المصعد",
  "from_camera": "من الكاميرا",
  "from_gallery": "من المعرض",
  "logout_confirmation": "هل أنت متأكد من تسجيل الخروج؟",
  "my_profile": "ملفي",
  "price": "السعر",
  "maintenance_required": "صيانة مطلوبة",
  "message": "رسالة",
  "chats": "المحادثات",
  "comments": "تعليقات",
  "delete": "حذف",
  "edit": "تحرير",
  "select_elevator_type": "من فضلك اختر نوع المصعد",
  "select_faults": "من فضلك اختر الاعطال",
  "select_date": "من فضلك اختر التاريخ",
  "write_notes": "من فضلك اكتب ملاحظاتك",
  "message_or_image_required": "لا بد من كتابة رسالة أو اختيار صورة لإرسالها",
  "no_data_found": "لا توجد بيانات",
  "messages": "رسائل",
  "password_changed": "تم تغيير كلمة المرور",
  "done": "تم"
};
static  Map<String,dynamic> en = {
  "test": "test",
  "choose_your_elevator": "Choose Your Elevator",
  "elevator_company_intro": "aknan elevator company provides you with different types of elevators suitable for individuals, companies and commercial centers",
  "maintenance_service": "Maintenance Service",
  "elevator_company_intro_2": "Aknan provides you with an integrated team of technicians to repair faults and perform permanent maintenance",
  "spare_parts": "Spare Parts",
  "elevator_company_intro_3": "Aknan elevator company provides \nyou with all the spare parts needed \nfor comprehensive maintenance of \nall types of elevators",
  "Phone_number": "Phone number",
  "get_started": "Get started",
  "Password": "Password",
  "forgot_password ": "Forgot Password ?",
  "Verify": "Verify",
  "your_phone": "your phone",
  "home": "Home",
  "chat": "Chat",
  "profile": "Profile",
  "settings": "Settings",
  "policies_privacy": "Policies & Privacy",
  "contact_us": "Contact Us",
  "change_password": "Change Password",
  "complete_data": "Complete data",
  "login": "LOGIN",
  "otp_login": "OTP Login",
  "or": "or",
  "do_not_have_an_account": "Don't have an account?",
  "sign_up": "REGISTER",
  "enter_verification_code": "Enter Verification Code",
  "did_not_receive_the_code": "Did not receive otp",
  "resend_it": "Resend",
  "reset_password": "Reset Password",
  "send_otp": "Send OTP",
  "save": "Save",
  "skip": "Skip",
  "enter_your_verified_phone_number": "Enter your verified phone number",
  "send": "SEND",
  "name": "Name",
  "email": "E-mail",
  "government": "Governrate",
  "city": "City",
  "district": "District",
  "confirm_password": "Confirm Password",
  "old_password": "Old Password",
  "new_password": "New Password",
  "confirm_new_password": "Confirm New Password",
  "update": "Update",
  "types_of_elevators": "Types Of Elevators",
  "maintenance_requests": "Maintenance Requests",
  "periodic": "Periodic",
  "emergency": "Emergency",
  "complaint": "Complaint",
  "Periodic": "Periodic",
  "Emergency": "Emergency",
  "Complaint": "Complaint",
  "notification": "Notification",
  "change_language": "Change Language",
  "theme": "Theme",
  "about_us": "About Us",
  "policies_and_privacy": "Policies And Privacy",
  "log_out": "Log Out",
  "contract_type": "Contract Type",
  "start_date": "Start Date",
  "end_date": "End Date",
  "periodic_maintenance": "Periodic Maintenance",
  "emergency_maintenance": "Emergency Maintenance",
  "complaint_maintenance": "Complaint Maintenance",
  "time_and_date": "Time & Date",
  "employee": "Employee",
  "cost": "Cost",
  "damage": "Damage",
  "maintenance_work": "Maintenance Work",
  "yes": "Yes",
  "no": "No",
  "change_password_confirmation": "Are you serious about changing the password?",
  "change_language_confirmation": "Are you serious about changing the language?",
  "ar": "Arabic",
  "en": "English",
  "request_maintenance": "Request A Maintenance",
  "malfunctions": "Malfunctions",
  "submit": "Submit",
  "next": "Next",
  "elevator_code": "Elevator Code",
  "from_camera": "From Camera",
  "from_gallery": "From Gallery",
  "logout_confirmation": "Are you sure to log out?",
  "my_profile": "My Profile",
  "price": "Price",
  "maintenance_required": "Maintenance Required",
  "message": "Message",
  "chats": "Chats",
  "comments": "Comments",
  "delete": "Delete",
  "edit": "Edit",
  "select_elevator_type": "Please select elevator type",
  "select_faults": "Please select faults",
  "select_date": "Please select the date",
  "write_notes": "Please write your notes",
  "message_or_image_required": "A message or an image is required for sending",
  "no_data_found": "No data found",
  "messages": "Messages",
  "password_changed": "Your Password has been changed",
  "done": "Done"
};
static  Map<String, Map<String,dynamic>> mapLocales = {"ar": ar, "en": en};
}
