name: aknan_user_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0+4

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  chucker_flutter: null
  country_code_picker:
    git:
      url: https://github.com/Alaabadr44/CountryCodePicker.git
      ref: main
  dartz: ^0.10.1
  dio: ^5.3.2
  dots_indicator: ^3.0.0
  dotted_border: ^2.1.0
  easy_localization: ^3.0.3
  equatable: ^2.0.5
  file_picker: ^6.1.1
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.9
  firebase_messaging: null
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^16.3.2
  flutter_native_splash: 2.3.7
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  flutter_widget_from_html_core: ^0.14.9
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  http_mock_adapter: ^0.6.1
  image_picker: ^1.0.7
  jiffy: ^6.2.1
  json_annotation: ^4.7.0
  lottie: 2.7.0
  multiselect: ^0.1.0
  one_context:
  permission_handler: 11.0.1
  photo_view: ^0.14.0
  pin_code_fields: null
  pretty_dio_logger: null
  pull_to_refresh: ^2.0.0
  restart_app: ^1.2.1
  retrofit: null
  shared_preferences: ^2.2.2
  socket_io_client: ^2.0.3+1
  qr_flutter:

# dependency_overrides: null
# dio: ^4.0.0
#   json_serializable: ^4.0.1
dev_dependencies:
  build_runner: null
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

  freezed: ^2.4.5
  retrofit_generator: null

flutter:
  uses-material-design: true

  assets:
    - assets/images/pngs/
    - assets/images/gifs/
    - assets/lottie/
    - assets/images/svgs/
    - assets/json/mockups/home/
    - assets/json/mockups/about/
    - assets/json/mockups/elevators-by-type/
    - assets/json/mockups/elevetors-list/
    - assets/json/mockups/New-Maintenance/
    - assets/json/mockups/Maintenance-work/
    - assets/json/mockups/add-maintenance/
    - assets/json/mockups/chats/
    - assets/json/mockups/chats/msgs-on-chat/
    - assets/translations/ar.json
    - assets/translations/en.json
    - shorebird.yaml

  fonts:
    - family: Inter
      fonts:
        - asset: assets/font/Inter/Inter-Thin.ttf
          weight: 100
        - asset: assets/font/Inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/font/Inter/Inter-Light.ttf
          weight: 300
        - asset: assets/font/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/font/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/font/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/font/Inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/font/Inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/font/Inter/Inter-Black.ttf
          weight: 900

flutter_assets:
  assets_path: assets/images/
  output_path: lib/global/app-assets
  filename: assets.dart
  field_prefix: null
